### ISSUE TITLE
pretrain_DNANet_model.tar这个文件损坏了，可以重新上传一下吗，非常感谢

### ISSUE THREAD

**Issue by Gyangustar1** [YeRen123455/Infrared-Small-Target-Detection#6]

**Comment by YeRen123455** [comment]
你好，我又试了一下，该模型可以正常使用

**Comment by Young-GG** [comment]
你好，这个解压时候显示损坏了，可以重新上传一下吗，或者能发给我的邮箱吗  480755534@qq.com

**Comment by YeRen123455** [comment]
@Young-GG  这个模型不需要解压，可以理解为类似于.pth的一种存储形式

**Comment by Young-GG** [comment]
你好，我在运行test_visulization.py时你提供的参数怎么写，

**Comment by Young-GG** [comment]
python test_and_visulization.py --base_size 256 --crop_size 256 --st_model [trained model path] --model_dir [model_dir] --dataset [dataset-name] --split_method 50_50 --model [model name] --backbone resnet_18  --deep_supervision True --test_batch_size 1 --mode TXT 
中的st_model和model_dir

**Comment by YeRen123455** [comment]
p retrain.tar不是最终模型，建议使用主页下方蓝色超链接的模型



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月05日 17:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [YeRen123455/Infrared-Small-Target-Detection] pretrain_DNANet_model.tar这个文件损坏了，可以重新上传一下吗，非常感谢 (#6) |

python test_and_visulization.py --base_size 256 --crop_size 256 --st_model [trained model path] --model_dir [model_dir] --dataset [dataset-name] --split_method 50_50 --model [model name] --backbone resnet_18 --deep_supervision True --test_batch_size 1 --mode TXT
中的st_model和model_dir

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Young-GG** [comment]
我不太明白你的st_model和model_dir分别要写什么内容

**Comment by Young-GG** [comment]
这两个看你的表述难道不是一样的吗

**Comment by Young-GG** [comment]
能解答一下吗，谢谢

**Comment by YeRen123455** [comment]
st 随便写   model dir 写准确路径



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月05日 17:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [YeRen123455/Infrared-Small-Target-Detection] pretrain_DNANet_model.tar这个文件损坏了，可以重新上传一下吗，非常感谢 (#6) |

能解答一下吗，谢谢

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Young-GG** [comment]
AttributeError: 'Namespace' object has no attribute 'save_dir'一直报这个错

**Comment by Young-GG** [comment]
运行test_visulization.py时，我在运行test_visulization.py时注释掉了from model.model_ACM    import  ACM，其他的也没改，不清楚是哪里出了问题。

**Comment by YeRen123455** [comment]
应该是普通的路径问题，这套代码实验室同学已经复现多遍，建议诸行查找路径错误

**Comment by YeRen123455** [comment]
应该是普通的路径问题，这套代码实验室同学已经复现多遍，建议逐行查找路径错误

**Comment by Young-GG** [comment]
能否给我一下你的这条命令的实例（你实际运行），我参考一下

**Comment by wssex** [comment]
> ###

> 运行test_visulization.py时，我在运行test_visulization.py时注释掉了from model.model_ACM import ACM，其他的也没改，不清楚是哪里出了问题。

你好，我也遇到了这种问题，请问这个地方你是怎么解决的呢？
