### ISSUE TITLE
请问MSvsGAN数据集是作者自己标注的嘛？可以提供的符合您代码要求吗？

### ISSUE THREAD

**Issue by BigModan** [YeRen123455/Infrared-Small-Target-Detection#9]

**Comment by YeRen123455** [comment]
你好，MDvsGAN数据集原作者有标注（本文中为方便区分，命名为NUST-SIRST），我没有修改其图像编号，你只需将图像放置指定位置即可。
















At 2021-12-15 16:20:22, "BigModen" ***@***.***> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
